# Generated by Django 5.2.3 on 2025-08-01 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpm_users', '0030_moderatorshortcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for the condition', max_length=100)),
                ('condition_type', models.CharField(choices=[('time_based', 'Time Based'), ('health_metric', 'Health Metric'), ('missed_reading', 'Missed Reading'), ('alert_triggered', 'Alert Triggered'), ('manual', 'Manual Trigger'), ('follow_up', 'Follow Up')], help_text='Type of condition that triggers calls', max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Configuration parameters for the condition (JSON format)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this condition is currently active')),
                ('description', models.TextField(blank=True, help_text='Detailed description of when this condition triggers')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority level for condition evaluation (1=highest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Condition',
                'verbose_name_plural': 'Call Conditions',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RetellCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retell_call_id', models.CharField(help_text='Unique call ID from Retell API', max_length=100, unique=True)),
                ('call_status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('from_number', models.CharField(help_text='Phone number used to make the call', max_length=20)),
                ('to_number', models.CharField(help_text="Patient's phone number", max_length=20)),
                ('start_timestamp', models.BigIntegerField(blank=True, help_text='Call start time as Unix timestamp', null=True)),
                ('end_timestamp', models.BigIntegerField(blank=True, help_text='Call end time as Unix timestamp', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Call duration in milliseconds', null=True)),
                ('transcript', models.TextField(blank=True, help_text='Full call transcript from Retell')),
                ('recording_url', models.URLField(blank=True, help_text='URL to call recording')),
                ('agent_id', models.CharField(blank=True, help_text='Retell agent ID used for the call', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retell_call_sessions', to='rpm_users.patient')),
            ],
            options={
                'verbose_name': 'Retell Call Session',
                'verbose_name_plural': 'Retell Call Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField(help_text='AI-generated summary of the call')),
                ('key_points', models.JSONField(default=list, help_text='List of key discussion points from the call')),
                ('concerning_flags', models.JSONField(default=list, help_text='List of concerning responses or red flags identified')),
                ('health_metrics', models.JSONField(default=dict, help_text='Structured health data extracted from the call')),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score for the summary (0.00-1.00)', max_digits=3, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(help_text='Patient associated with this summary', on_delete=django.db.models.deletion.CASCADE, related_name='call_summaries', to='rpm_users.patient')),
                ('call_session', models.OneToOneField(help_text='Associated call session', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='retell_calling.retellcallsession')),
            ],
            options={
                'verbose_name': 'Call Summary',
                'verbose_name_plural': 'Call Summaries',
                'ordering': ['-generated_at'],
            },
        ),
    ]
