# Generated by Django 5.2.3 on 2025-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retell_calling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retellcallsession',
            name='ai_summary',
            field=models.JSONField(blank=True, help_text='AI-generated summary and analysis', null=True),
        ),
        migrations.AddField(
            model_name='retellcallsession',
            name='call_analysis',
            field=models.JSONField(blank=True, help_text="Retell's call analysis data", null=True),
        ),
        migrations.AddField(
            model_name='retellcallsession',
            name='disconnection_reason',
            field=models.CharField(blank=True, help_text='Reason for call disconnection', max_length=50),
        ),
        migrations.AddField(
            model_name='retellcallsession',
            name='transcript_object',
            field=models.JSONField(blank=True, help_text='Structured transcript object from Retell', null=True),
        ),
    ]
