# Generated by Django 5.2.5 on 2025-10-02 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retell_calling', '0002_retellcallsession_ai_summary_and_more'),
        ('rpm_users', '0035_alter_interestpastmedicalhistory_pmh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retell_call_id', models.CharField(help_text='Unique call ID from Retell API', max_length=100, unique=True)),
                ('call_status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('from_number', models.CharField(help_text='Phone number used to make the call', max_length=20)),
                ('to_number', models.CharField(help_text="Lead's phone number", max_length=20)),
                ('start_timestamp', models.BigIntegerField(blank=True, help_text='Call start time as Unix timestamp', null=True)),
                ('end_timestamp', models.BigIntegerField(blank=True, help_text='Call end time as Unix timestamp', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Call duration in milliseconds', null=True)),
                ('transcript', models.TextField(blank=True, help_text='Full call transcript from Retell')),
                ('transcript_object', models.JSONField(blank=True, help_text='Structured transcript object from Retell', null=True)),
                ('recording_url', models.URLField(blank=True, help_text='URL to call recording')),
                ('agent_id', models.CharField(blank=True, help_text='Retell agent ID used for the call', max_length=100)),
                ('disconnection_reason', models.CharField(blank=True, help_text='Reason for call disconnection', max_length=50)),
                ('ai_summary', models.JSONField(blank=True, help_text='AI-generated summary and analysis', null=True)),
                ('call_analysis', models.JSONField(blank=True, help_text="Retell's call analysis data", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_call_sessions', to='rpm_users.interestlead')),
            ],
            options={
                'verbose_name': 'Lead Call Session',
                'verbose_name_plural': 'Lead Call Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCallSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField(help_text='AI-generated summary of the call')),
                ('key_points', models.JSONField(default=list, help_text='List of key discussion points from the call')),
                ('concerning_flags', models.JSONField(default=list, help_text='List of concerning responses or red flags identified')),
                ('health_metrics', models.JSONField(default=dict, help_text='Structured health data extracted from the call')),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score for the summary (0.00-1.00)', max_digits=3, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.OneToOneField(help_text='Associated lead call session', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='retell_calling.leadcallsession')),
                ('lead', models.ForeignKey(help_text='Lead associated with this summary', on_delete=django.db.models.deletion.CASCADE, related_name='lead_call_summaries', to='rpm_users.interestlead')),
            ],
            options={
                'verbose_name': 'Lead Call Summary',
                'verbose_name_plural': 'Lead Call Summaries',
                'ordering': ['-generated_at'],
            },
        ),
    ]
