# Generated by Django 5.2.5 on 2025-10-11 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retell_calling', '0003_leadcallsession_leadcallsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('lead_calls', 'Lead Calls'), ('patient_calls', 'Patient Calls')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('total_leads', models.PositiveIntegerField(help_text='Total number of leads/patients to call')),
                ('leads_data', models.JSONField(help_text='List of leads/patients data')),
                ('agent_id', models.CharField(help_text='Retell agent ID to use for calls', max_length=100)),
                ('current_index', models.PositiveIntegerField(default=0, help_text='Current position in the leads list')),
                ('successful_calls', models.PositiveIntegerField(default=0)),
                ('failed_calls', models.PositiveIntegerField(default=0)),
                ('completed_calls', models.PositiveIntegerField(default=0)),
                ('call_results', models.JSONField(default=list, help_text='Results of each call attempt')),
                ('error_message', models.TextField(blank=True, help_text='Error message if session failed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bulk Call Session',
                'verbose_name_plural': 'Bulk Call Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leadcallsession',
            name='bulk_session_id',
            field=models.UUIDField(blank=True, help_text='Associated bulk calling session', null=True),
        ),
    ]
