# Generated by Django 5.2.5 on 2025-10-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retell_calling', '0004_bulkcallsession_leadcallsession_bulk_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcallsession',
            name='busy_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkcallsession',
            name='no_answer_calls',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
