# Generated by Django 5.2.4 on 2026-04-29 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retell_calling', '0005_bulkcallsession_busy_calls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bulk_session_id', models.UUIDField(blank=True, help_text='Associated bulk calling session', null=True)),
                ('retell_call_id', models.CharField(help_text='Unique call ID from Retell API', max_length=100, unique=True)),
                ('call_status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('from_number', models.CharField(help_text='Phone number used to make the call', max_length=20)),
                ('to_number', models.CharField(help_text='Facility phone number', max_length=20)),
                ('start_timestamp', models.BigIntegerField(blank=True, help_text='Call start time as Unix timestamp', null=True)),
                ('end_timestamp', models.BigIntegerField(blank=True, help_text='Call end time as Unix timestamp', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Call duration in milliseconds', null=True)),
                ('transcript', models.TextField(blank=True, help_text='Full call transcript from Retell')),
                ('transcript_object', models.JSONField(blank=True, help_text='Structured transcript object from Retell', null=True)),
                ('recording_url', models.URLField(blank=True, help_text='URL to call recording')),
                ('agent_id', models.CharField(blank=True, help_text='Retell agent ID used for the call', max_length=100)),
                ('disconnection_reason', models.CharField(blank=True, help_text='Reason for call disconnection', max_length=50)),
                ('ai_summary', models.JSONField(blank=True, help_text='AI-generated summary and analysis', null=True)),
                ('call_analysis', models.JSONField(blank=True, help_text="Retell's call analysis data", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility Call Session',
                'verbose_name_plural': 'Facility Call Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityCallTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_missing_in', models.CharField(blank=True, max_length=255, null=True)),
                ('notes_type', models.TextField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_row_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('call_attempts', models.PositiveIntegerField(default=0)),
                ('last_call_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_extracted_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_summary_text', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility Call Target',
                'verbose_name_plural': 'Facility Call Targets',
                'ordering': ['facility_name', 'city'],
            },
        ),
        migrations.AlterField(
            model_name='bulkcallsession',
            name='session_type',
            field=models.CharField(choices=[('lead_calls', 'Lead Calls'), ('patient_calls', 'Patient Calls'), ('facility_calls', 'Facility Calls')], max_length=20),
        ),
        migrations.CreateModel(
            name='FacilityCallSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField(help_text='AI-generated summary of the call')),
                ('key_points', models.JSONField(default=list, help_text='List of key discussion points from the call')),
                ('concerning_flags', models.JSONField(default=list, help_text='List of concerning responses or red flags identified')),
                ('extracted_email', models.EmailField(blank=True, help_text='Email address extracted from the call', max_length=254, null=True)),
                ('contact_name', models.CharField(blank=True, help_text='Name of the person who answered', max_length=255, null=True)),
                ('contact_title', models.CharField(blank=True, help_text='Title of the contact person', max_length=255, null=True)),
                ('reached_right_person', models.BooleanField(default=False, help_text='Whether the call reached the correct decision-maker')),
                ('email_obtained', models.BooleanField(default=False, help_text='Whether an email address was obtained')),
                ('call_disposition', models.CharField(choices=[('right_person_email', 'Reached right person and got email'), ('right_person_no_email', 'Reached right person but no email'), ('wrong_person', 'Did not reach the right person'), ('no_answer', 'No answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score for the summary (0.00-1.00)', max_digits=3, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.OneToOneField(help_text='Associated facility call session', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='retell_calling.facilitycallsession')),
                ('facility', models.ForeignKey(help_text='Facility associated with this summary', on_delete=django.db.models.deletion.CASCADE, related_name='facility_call_summaries', to='retell_calling.facilitycalltarget')),
            ],
            options={
                'verbose_name': 'Facility Call Summary',
                'verbose_name_plural': 'Facility Call Summaries',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='facilitycallsession',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_call_sessions', to='retell_calling.facilitycalltarget'),
        ),
    ]
