# Generated by Django 5.2.5 on 2025-09-21 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpm_users', '0033_patient_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_names', models.JSONField(blank=True, default=list)),
                ('drug_class', models.CharField(blank=True, max_length=255, null=True)),
                ('mechanism', models.TextField(blank=True, null=True)),
                ('dosage', models.TextField(blank=True, null=True)),
                ('administration', models.TextField(blank=True, null=True)),
                ('side_effects', models.JSONField(blank=True, default=list)),
                ('contraindications', models.JSONField(blank=True, default=list)),
                ('drug_interactions', models.JSONField(blank=True, default=list)),
                ('monitoring', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('fda_approved', models.BooleanField(default=True)),
                ('pregnancy_category', models.CharField(blank=True, max_length=10, null=True)),
                ('controlled_substance', models.BooleanField(default=False)),
                ('gemini_confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Gemini AI confidence score (0.00-1.00)', max_digits=5, null=True)),
                ('last_updated_from_ai', models.DateTimeField(auto_now_add=True)),
                ('ai_source_version', models.CharField(default='gemini-pro', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('last_searched', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.TextField(blank=True, null=True)),
                ('is_first_line', models.BooleanField(default=False)),
                ('is_off_label', models.BooleanField(default=False)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_treatments', to='medications.disease')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_indications', to='medications.medicine')),
            ],
            options={
                'ordering': ['-is_first_line', 'medicine__name'],
            },
        ),
        migrations.CreateModel(
            name='CachedMedicineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medicine')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='MedicineInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], max_length=20)),
                ('description', models.TextField()),
                ('management', models.TextField(blank=True, null=True)),
                ('clinical_significance', models.TextField(blank=True, null=True)),
                ('onset', models.CharField(blank=True, max_length=100, null=True)),
                ('documentation', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='medications.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='medications.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(db_index=True, max_length=500, unique=True)),
                ('normalized_query', models.CharField(db_index=True, max_length=500)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('ai_response_raw', models.JSONField(blank=True, null=True)),
                ('ai_processing_time', models.FloatField(blank=True, null=True)),
                ('medicines', models.ManyToManyField(through='medications.CachedMedicineResult', to='medications.medicine')),
            ],
            options={
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.AddField(
            model_name='cachedmedicineresult',
            name='cache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medicinesearchcache'),
        ),
        migrations.CreateModel(
            name='PatientMedicineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=500)),
                ('interaction_checked', models.BooleanField(default=False)),
                ('interaction_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.disease')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_searches', to='rpm_users.patient')),
                ('viewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='medications_name_205c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name'], name='medications_generic_cdd84d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['drug_class'], name='medications_drug_cl_2be217_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['last_searched'], name='medications_last_se_c6bc9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diseasemedicine',
            unique_together={('disease', 'medicine')},
        ),
        migrations.AlterUniqueTogether(
            name='medicineinteraction',
            unique_together={('medicine_a', 'medicine_b')},
        ),
        migrations.AlterUniqueTogether(
            name='cachedmedicineresult',
            unique_together={('cache', 'medicine')},
        ),
    ]
