# Generated by Django 5.2.3 on 2025-06-28 19:46

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpm_users', '0029_alter_interestpastmedicalhistory_pmh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_call_duration', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('max_daily_retries', models.PositiveIntegerField(default=3)),
                ('ai_model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('voice_model', models.CharField(default='tts-1', max_length=50)),
                ('enable_recording', models.BooleanField(default=True)),
                ('emergency_keywords', models.JSONField(default=list, help_text='Keywords that trigger immediate alerts')),
                ('business_hours_start', models.TimeField(default='09:00')),
                ('business_hours_end', models.TimeField(default='17:00')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallQuestionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='The question to ask the patient')),
                ('question_type', models.CharField(choices=[('scale', 'Scale (1-10)'), ('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('open_ended', 'Open Ended'), ('numeric', 'Numeric Value')], max_length=20)),
                ('options', models.JSONField(blank=True, help_text='For multiple choice questions, store options as JSON array', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to ask questions')),
                ('is_required', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('follow_up_conditions', models.JSONField(blank=True, help_text='Conditions that trigger follow-up questions', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='CallSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('preferred_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1)),
                ('preferred_time', models.TimeField(help_text="Preferred time for calls in patient's timezone")),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_schedules', to='rpm_users.patient')),
            ],
            options={
                'unique_together': {('patient', 'frequency')},
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('call_duration', models.DurationField(blank=True, null=True)),
                ('call_sid', models.CharField(blank=True, help_text='Twilio Call SID', max_length=100, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from the call')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='calling_agent.callschedule')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='rpm_users.patient')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='CallResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField(help_text='Raw response from patient')),
                ('processed_response', models.TextField(blank=True, help_text='AI-processed/cleaned response', null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence in response understanding (0-1)', max_digits=3, null=True)),
                ('is_concerning', models.BooleanField(default=False, help_text='Flagged as concerning by AI')),
                ('requires_followup', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling_agent.callquestiontemplate')),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='calling_agent.callsession')),
            ],
            options={
                'unique_together': {('call_session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='CallAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('critical_response', 'Critical Response'), ('missed_call', 'Missed Call'), ('concerning_trend', 'Concerning Trend'), ('technical_failure', 'Technical Failure')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_alerts', to='rpm_users.patient')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_call_alerts', to=settings.AUTH_USER_MODEL)),
                ('call_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='calling_agent.callresponse')),
                ('call_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='calling_agent.callsession')),
            ],
            options={
                'ordering': ['-created_at', '-severity'],
            },
        ),
    ]
