# Generated by Django 5.2.5 on 2025-10-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=100)),
                ('patient_phone', models.CharField(max_length=15)),
                ('referred_by', models.CharField(max_length=100)),
                ('referred_by_email', models.EmailField(max_length=100)),
                ('contacted', models.BooleanField(default=False)),
                ('referrer_rewarded', models.BooleanField(default=False)),
                ('referral_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
