# Generated by Django 5.1 on 2024-12-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documentations/'),
        ),
    ]
