# Generated by Django 5.1 on 2025-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_documentation_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='cheif_complaint',
            new_name='chief_complaint',
        ),
        migrations.AlterField(
            model_name='documentation',
            name='title',
            field=models.CharField(choices=[('Progress Note', 'Progress Note')], default='Progress Note', max_length=255),
        ),
    ]
