# Generated by Django 5.1 on 2025-04-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_description_documentation_history_of_present_illness_and_more'),
        ('rpm_users', '0015_rename_drink_smoke_patient_drink_patient_smoke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='report',
        ),
        migrations.AddField(
            model_name='documentation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='rpm_users.patient'),
        ),
    ]
