# Generated by Django 5.1 on 2025-04-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_documentation_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='report',
        ),
    ]
