# Generated by Django 5.2.1 on 2025-05-28 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reports_battery_level_reports_blood_glucose_and_more'),
        ('rpm_users', '0024_patient_insurance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='written_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='rpm_users.moderator'),
        ),
    ]
