# Generated by Django 5.2.3 on 2025-06-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_documentation_patient_snapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='patient_clinical_staff',
            new_name='doc_clinical_staff',
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='patient_date_of_birth',
            new_name='doc_dob',
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='patient_moderator',
            new_name='doc_moderator',
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='patient_monitoring_parameters',
            new_name='doc_monitoring_params',
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='patient_name',
            new_name='doc_patient_name',
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='patient_report_date',
            new_name='doc_report_date',
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='patient_sex',
            new_name='doc_sex',
        ),
    ]
