# Generated by Django 5.2.5 on 2025-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_documentation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='title',
            field=models.CharField(choices=[('CCM Initial Note', 'CCM Initial Note'), ('CCM Note Clinical Staff', 'CCM Note Clinical Staff'), ('CCM Note, MD', 'CCM Note, MD'), ('CCM Note NP/PA', 'CCM Note NP/PA'), ('E-Visit Followup Note MD', 'E-Visit Followup Note MD'), ('E-Visit Followup Note NP/PA', 'E-Visit Followup Note NP/PA'), ('Inpatient Hospital Note', 'Inpatient Hospital Note'), ('Occupation Therapy Note', 'Occupation Therapy Note'), ('Office Visit Note MD', 'Office Visit Note MD'), ('Office Visit Note NP/PA', 'Office Visit Note NP/PA'), ('Physical Therapy Note', 'Physical Therapy Note'), ('Progress Note', 'Progress Note'), ('Rehabilitation MD Note', 'Rehabilitation MD Note'), ('RPM Note, Clinical Staff', 'RPM Note, Clinical Staff'), ('RPM Progress Note', 'RPM Progress Note'), ('Skilled Nursing Note MD', 'Skilled Nursing Note MD'), ('Skilled Nursing Note NP/PA', 'Skilled Nursing Note NP/PA'), ('Speech Therapy Note', 'Speech Therapy Note'), ('Telehealth Visit MD', 'Telehealth Visit MD'), ('Telehealth Visit NP/PA', 'Telehealth Visit NP/PA'), ('Telephone Visit Initiated By Patient', 'Telephone Visit Initiated By Patient'), ('Transitional Care Note MD', 'Transitional Care Note MD'), ('Transitional Care Note NP/PA', 'Transitional Care Note NP/PA')], default='Progress Note', max_length=255),
        ),
    ]
