# Generated by Django 5.2.5 on 2025-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_documentation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='title',
            field=models.CharField(choices=[('CCM Initial Note', 'CCM Initial Note'), ('CCM Note Clinical Staff', 'CCM Note Clinical Staff'), ('CCM Note NP/PA', 'CCM Note NP/PA'), ('CCM Note Physician', 'CCM Note Physician'), ('CCM-HTN Progress Note', 'CCM-HTN Progress Note'), ('E-Visit Followup Note MD', 'E-Visit Followup Note MD'), ('E-Visit Followup Note MD NP/PA', 'E-Visit Followup Note MD NP/PA'), ('Inpatient Hospital H&P Physician', 'Inpatient Hospital H&P Physician'), ('Occupation Therapy Note', 'Occupation Therapy Note'), ('Office Visit Note MD', 'Office Visit Note MD'), ('Office Visit Note NP/PA', 'Office Visit Note NP/PA'), ('Physical Therapy Note', 'Physical Therapy Note'), ('Progress Note', 'Progress Note'), ('Rehabilitation MD Note', 'Rehabilitation MD Note'), ('RPM Note Clinical Staff', 'RPM Note Clinical Staff'), ('RPM Progress Note', 'RPM Progress Note'), ('Skilled Nursing Consult', 'Skilled Nursing Consult'), ('Skilled Nursing H&P', 'Skilled Nursing H&P'), ('Skilled Nursing Note', 'Skilled Nursing Note'), ('Speech Therapy Note', 'Speech Therapy Note'), ('Telehealth Initial Visit Physician', 'Telehealth Initial Visit Physician'), ('Telehealth Visit NP/PA', 'Telehealth Visit NP/PA'), ('Telehealth Visit Physician', 'Telehealth Visit Physician'), ('Telephone Visit Initiated By Patient', 'Telephone Visit Initiated By Patient'), ('Transitional Care Note NP/PA', 'Transitional Care Note NP/PA'), ('Transitional Care Note Physician', 'Transitional Care Note Physician')], default='Progress Note', max_length=255),
        ),
    ]
