# Generated by Django 5.2.5 on 2025-12-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_documentation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='manual_datetime',
            field=models.DateTimeField(blank=True, help_text='Manual date/time for when vitals were taken', null=True),
        ),
    ]
