# Generated by Django 5.1 on 2024-09-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
