# Generated by Django 5.1 on 2024-10-07 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0002_alter_patient_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='moderator_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderators', to='rpm_users.moderator'),
        ),
    ]
