# Generated by Django 5.1 on 2024-10-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0003_alter_patient_moderator_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='wight',
            new_name='weight',
        ),
    ]
