# Generated by Django 5.1 on 2025-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0011_alter_patient_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='device_serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='monitoring_parameters',
            field=models.CharField(blank=True, choices=[('Blood Pressure', 'Blood Pressure'), ('Heart Rate', 'Heart Rate'), ('SPO2', 'SPO2'), ('Temperature', 'Temperature')], max_length=20, null=True),
        ),
    ]
