# Generated by Django 5.1 on 2025-04-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0012_patient_device_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pharmacy_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
