# Generated by Django 5.1 on 2025-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0014_patient_allergies_patient_drink_smoke_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='drink_smoke',
            new_name='drink',
        ),
        migrations.AddField(
            model_name='patient',
            name='smoke',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
    ]
