# Generated by Django 5.1 on 2025-04-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0015_rename_drink_smoke_patient_drink_patient_smoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
