# Generated by Django 5.1 on 2025-04-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0016_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='device_serial_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
