# Generated by Django 5.1 on 2025-05-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0017_alter_patient_device_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='device_serial_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
