# Generated by Django 5.1 on 2025-05-13 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0018_alter_patient_device_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('insurance', models.CharField(max_length=255)),
                ('service_interest', models.CharField(choices=[('blood_pressure', 'Blood Pressure Monitoring'), ('heart_rate', 'Heart Rate Monitoring'), ('oxygen', 'Oxygen Saturation (O₂)'), ('diabetes', 'Diabetes Management')], max_length=20)),
                ('good_eyesight', models.BooleanField(default=False)),
                ('can_follow_instructions', models.BooleanField(default=False)),
                ('can_take_readings', models.BooleanField(default=False)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestPastMedicalHistory',
            fields=[
                ('pmh', models.CharField(choices=[('GBS', 'Guillain-Barré Syndrome'), ('ALS', 'Amyotrophic Lateral Sclerosis'), ('SLE', 'Systemic Lupus Erythematosus'), ('ITP', 'Idiopathic Thrombocytopenic Purpura'), ('MG', 'Myasthenia Gravis'), ('DKA', 'Diabetic Ketoacidosis'), ('ARDS', 'Acute Respiratory Distress Syndrome'), ('LCa', 'Lung Cancer'), ('PCa', 'Pancreatic Cancer'), ('CCa', 'Colon Cancer'), ('TCa', 'Thyroid Cancer'), ('SCa', 'Skin Cancer'), ('GCa', 'Gastric Cancer'), ('PCa', 'Prostate Cancer'), ('TeCa', 'Testicular Cancer'), ('BrCa', 'Breast Cancer'), ('OvCa', 'Ovarian Cancer'), ('TTP', 'Thrombotic Thrombocytopenic Purpura'), ('HLH', 'Hemophagocytic Lymphohistiocytosis'), ('HSP', 'Henoch-Schönlein Purpura'), ('SCID', 'Severe Combined Immunodeficiency'), ('PKU', 'Phenylketonuria'), ('POTS', 'Postural Orthostatic Tachycardia Syndrome'), ('CRPS', 'Complex Regional Pain Syndrome'), ('NMO', 'Neuromyelitis Optica'), ('HUS', 'Hemolytic Uremic Syndrome'), ('SMA', 'Spinal Muscular Atrophy'), ('DM', 'Diabetes Mellitus'), ('HTN', 'Hypertension'), ('AF', 'Atrial Fibrillation'), ('CHF', 'Congestive Heart Failure'), ('COPD', 'Chronic Obstructive Pulmonary Disease'), ('Hpxa', 'Hypoxia'), ('Hyca', 'Hypercapnea'), ('CKD', 'Chronic Kidney Disease'), ('ESRD', 'End Stage Renal Disease'), ('GERD', 'Gastroesophageal Reflux Disease'), ('OA', 'Osteoarthritis'), ('CAD', 'Coronary Artery Disease'), ('RA', 'Rheumatoid Arthritis'), ('UTI', 'Urinary Tract Infection'), ('URI', 'Upper Respiratory Infection'), ('BPH', 'Benign Prostatic Hyperplasia'), ('HLD', 'Hyperlipidemia'), ('TIA', 'Transient Ischemic Attack'), ('CVA', 'Cerebrovascular Accident (Stroke)'), ('MI', 'Myocardial Infarction'), ('PNA', 'Pneumonia'), ('TB', 'Tuberculosis'), ('HIV', 'Human Immunodeficiency Virus'), ('ADHD', 'Attention-Deficit/Hyperactivity Disorder'), ('ASD', 'Autism Spectrum Disorder'), ('MDD', 'Major Depressive Disorder'), ('GAD', 'Generalized Anxiety Disorder'), ('PTSD', 'Post-Traumatic Stress Disorder'), ('Peff', 'Pleural Effusion'), ('N/A', 'N/A')], max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='rpm_users.interest')),
            ],
        ),
    ]
