# Generated by Django 5.1 on 2025-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0020_interestlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestlead',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
