# Generated by Django 5.1 on 2025-05-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0021_interestlead_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestlead',
            name='past_medical_history',
        ),
    ]
