# Generated by Django 5.1 on 2025-05-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0022_remove_interestlead_past_medical_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestlead',
            name='can_follow_instructions',
        ),
        migrations.RemoveField(
            model_name='interestlead',
            name='can_take_readings',
        ),
        migrations.RemoveField(
            model_name='interestlead',
            name='good_eyesight',
        ),
    ]
