# Generated by Django 5.2.1 on 2025-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0024_patient_insurance_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='service_interest',
            field=models.CharField(choices=[('blood_pressure', 'Blood Pressure Monitoring'), ('heart_rate', 'Heart Rate Monitoring'), ('oxygen', 'Oxygen Saturation(O₂)'), ('diabetes', 'Diabetes Management')], max_length=20),
        ),
    ]
