# Generated by Django 5.2.1 on 2025-06-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0026_patient_is_escalated_doctor_patient_doctor_escalated'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
