# Generated by Django 5.2.3 on 2025-06-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0027_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='moderator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
