# Generated by Django 5.2.3 on 2025-07-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0029_alter_interestpastmedicalhistory_pmh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut_key', models.CharField(help_text="The shortcut key (e.g., '.pe')", max_length=50)),
                ('description', models.CharField(help_text='Brief description of the shortcut', max_length=255)),
                ('content', models.TextField(help_text='The full text content that replaces the shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='rpm_users.moderator')),
            ],
            options={
                'ordering': ['shortcut_key'],
                'unique_together': {('moderator', 'shortcut_key')},
            },
        ),
    ]
