# Generated by Django 5.2.5 on 2025-09-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0032_alter_interestpastmedicalhistory_pmh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact person name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship to patient', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_address',
            field=models.TextField(blank=True, help_text='Complete home address for machine delivery', null=True),
        ),
    ]
