# Generated by Django 5.2.5 on 2025-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0033_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_care_physician',
            field=models.CharField(blank=True, help_text='Primary Care Physician name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_care_physician_phone',
            field=models.CharField(blank=True, help_text='Primary Care Physician phone number', max_length=15, null=True),
        ),
    ]
