# Generated by Django 5.2.5 on 2025-10-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0035_alter_interestpastmedicalhistory_pmh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestlead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interestlead',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interestlead',
            name='mrn_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MRN#'),
        ),
        migrations.AddField(
            model_name='interestlead',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='interestlead',
            name='primary_insured_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interestlead',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='interestlead',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interestlead',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
