# Generated by Django 5.2.5 on 2025-12-25 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0041_alter_interestpastmedicalhistory_pmh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestpastmedicalhistory',
            name='pmh',
            field=models.CharField(choices=[('ARDS', 'Acute Respiratory Distress Syndrome'), ('ADHD', 'Attention-Deficit/Hyperactivity Disorder'), ('ALS', 'Amyotrophic Lateral Sclerosis'), ('ASD', 'Autism Spectrum Disorder'), ('ETOH', 'Alcohol use'), ('HGB', 'Anemia'), ('AdInsuff', 'Adrenal insufficiency'), ('AF', 'Atrial Fibrillation'), ('BPH', 'Benign Prostatic Hyperplasia'), ('BrCa', 'Breast Cancer'), ('CVA', 'Cerebrovascular Accident (Stroke)'), ('CHAR', 'Charcot'), ('CKD', 'Chronic Kidney Disease'), ('COPD', 'Chronic Obstructive Pulmonary Disease'), ('CCa', 'Colon Cancer'), ('CRPS', 'Complex Regional Pain Syndrome'), ('CHF', 'Congestive Heart Failure'), ('ChrPn', 'Chronic Pain'), ('Const', 'Constipation'), ('CAD', 'Coronary Artery Disease'), ('DKA', 'Diabetic Ketoacidosis'), ('DMK', ' Diabetic nephropathy (kidney)'), ('DMN', 'Diabetic neuropathy'), ('DMR', 'Diabetic retinopathy'), ('DM', 'Diabetes Mellitus'), ('ESRD', 'End Stage Renal Disease'), ('Femr', 'Femur Fracture'), ('GCa', 'Gastric Cancer'), ('GERD', 'Gastroesophageal Reflux Disease'), ('GAD', 'Generalized Anxiety Disorder'), ('Gitis', 'Gastritis '), ('GIB', 'GI bleed'), ('GBS', 'Guillain-Barré Syndrome'), ('HLH', 'Hemophagocytic Lymphohistiocytosis'), ('HUS', 'Hemolytic Uremic Syndrome'), ('HUMR', 'Humerus FX'), ('HSP', 'Henoch-Schönlein Purpura'), ('HIV', 'Human Immunodeficiency Virus'), ('Hyca', 'Hypercapnea'), ('Hypo', 'Hypotension'), ('HpTh', 'Hypothyroidism'), ('HLD', 'Hyperlipidemia'), ('Hpxa', 'Hypoxia'), ('HTN', 'Hypertension'), ('Insm', 'Insomnia'), ('ITP', 'Idiopathic Thrombocytopenic Purpura'), ('LCa', 'Lung Cancer'), ('MDD', 'Major Depressive Disorder'), ('MOB', 'Morbid Obesity'), ('MI', 'Myocardial Infarction'), ('MG', 'Myasthenia Gravis'), ('MVP', 'Mitral Valve Prolapse'), ('N/A', 'N/A'), ('NMO', 'Neuromyelitis Optica'), ('Npathy', 'Neuropathy'), ('OA', 'Osteoarthritis'), ('OvCa', 'Ovarian Cancer'), ('PCa', 'Pancreatic Cancer'), ('PKU', 'Phenylketonuria'), ('Peff', 'Pleural Effusion'), ('PNA', 'Pneumonia'), ('POTS', 'Postural Orthostatic Tachycardia Syndrome'), ('PTSD', 'Post-Traumatic Stress Disorder'), ('PrCa', 'Prostate Cancer'), ('RA', 'Rheumatoid Arthritis'), ('SCID', 'Severe Combined Immunodeficiency'), ('SCa', 'Skin Cancer'), ('SVT', 'Supra Ventricular Tachycardia'), ('OSA', 'Sleep apnea'), ('SMA', 'Spinal Muscular Atrophy'), ('SLE', 'Systemic Lupus Erythematosus'), ('TeCa', 'Testicular Cancer'), ('TCa', 'Thyroid Cancer'), ('TTP', 'Thrombotic Thrombocytopenic Purpura'), ('TIA', 'Transient Ischemic Attack'), ('Tachy', 'Tachycardia '), ('TB', 'Tuberculosis'), ('UTI', 'Urinary Tract Infection'), ('URI', 'Upper Respiratory Infection'), ('VF', 'Valley Fever')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='pmh',
            field=models.CharField(choices=[('ARDS', 'Acute Respiratory Distress Syndrome'), ('ADHD', 'Attention-Deficit/Hyperactivity Disorder'), ('ALS', 'Amyotrophic Lateral Sclerosis'), ('ASD', 'Autism Spectrum Disorder'), ('ETOH', 'Alcohol use'), ('HGB', 'Anemia'), ('AdInsuff', 'Adrenal insufficiency'), ('AF', 'Atrial Fibrillation'), ('BPH', 'Benign Prostatic Hyperplasia'), ('BrCa', 'Breast Cancer'), ('CVA', 'Cerebrovascular Accident (Stroke)'), ('CHAR', 'Charcot'), ('CKD', 'Chronic Kidney Disease'), ('COPD', 'Chronic Obstructive Pulmonary Disease'), ('CCa', 'Colon Cancer'), ('CRPS', 'Complex Regional Pain Syndrome'), ('CHF', 'Congestive Heart Failure'), ('ChrPn', 'Chronic Pain'), ('Const', 'Constipation'), ('CAD', 'Coronary Artery Disease'), ('DKA', 'Diabetic Ketoacidosis'), ('DMK', ' Diabetic nephropathy (kidney)'), ('DMN', 'Diabetic neuropathy'), ('DMR', 'Diabetic retinopathy'), ('DM', 'Diabetes Mellitus'), ('ESRD', 'End Stage Renal Disease'), ('Femr', 'Femur Fracture'), ('GCa', 'Gastric Cancer'), ('GERD', 'Gastroesophageal Reflux Disease'), ('GAD', 'Generalized Anxiety Disorder'), ('Gitis', 'Gastritis '), ('GIB', 'GI bleed'), ('GBS', 'Guillain-Barré Syndrome'), ('HLH', 'Hemophagocytic Lymphohistiocytosis'), ('HUS', 'Hemolytic Uremic Syndrome'), ('HUMR', 'Humerus FX'), ('HSP', 'Henoch-Schönlein Purpura'), ('HIV', 'Human Immunodeficiency Virus'), ('Hyca', 'Hypercapnea'), ('Hypo', 'Hypotension'), ('HpTh', 'Hypothyroidism'), ('HLD', 'Hyperlipidemia'), ('Hpxa', 'Hypoxia'), ('HTN', 'Hypertension'), ('Insm', 'Insomnia'), ('ITP', 'Idiopathic Thrombocytopenic Purpura'), ('LCa', 'Lung Cancer'), ('MDD', 'Major Depressive Disorder'), ('MOB', 'Morbid Obesity'), ('MI', 'Myocardial Infarction'), ('MG', 'Myasthenia Gravis'), ('MVP', 'Mitral Valve Prolapse'), ('N/A', 'N/A'), ('NMO', 'Neuromyelitis Optica'), ('Npathy', 'Neuropathy'), ('OA', 'Osteoarthritis'), ('OvCa', 'Ovarian Cancer'), ('PCa', 'Pancreatic Cancer'), ('PKU', 'Phenylketonuria'), ('Peff', 'Pleural Effusion'), ('PNA', 'Pneumonia'), ('POTS', 'Postural Orthostatic Tachycardia Syndrome'), ('PTSD', 'Post-Traumatic Stress Disorder'), ('PrCa', 'Prostate Cancer'), ('RA', 'Rheumatoid Arthritis'), ('SCID', 'Severe Combined Immunodeficiency'), ('SCa', 'Skin Cancer'), ('SVT', 'Supra Ventricular Tachycardia'), ('OSA', 'Sleep apnea'), ('SMA', 'Spinal Muscular Atrophy'), ('SLE', 'Systemic Lupus Erythematosus'), ('TeCa', 'Testicular Cancer'), ('TCa', 'Thyroid Cancer'), ('TTP', 'Thrombotic Thrombocytopenic Purpura'), ('TIA', 'Transient Ischemic Attack'), ('Tachy', 'Tachycardia '), ('TB', 'Tuberculosis'), ('UTI', 'Urinary Tract Infection'), ('URI', 'Upper Respiratory Infection'), ('VF', 'Valley Fever')], default='N/A', max_length=100),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text="Customer's name to display", max_length=255)),
                ('customer_image', models.ImageField(blank=True, help_text="Customer's photo", null=True, upload_to='testimonials/')),
                ('review_text', models.TextField(help_text="Customer's review/testimonial text")),
                ('rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5 stars')),
                ('location', models.CharField(blank=True, help_text="Customer's location (e.g., 'New York, NY')", max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to show on landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
