# Generated by Django 5.2.4 on 2025-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0043_alter_interestpastmedicalhistory_pmh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('GREEN', 'Green'), ('ORANGE', 'Orange')], default='GREEN', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sticky_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
