# Generated by Django 5.2.5 on 2025-12-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0044_patient_status_patient_sticky_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='green', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sticky_note',
            field=models.TextField(blank=True, help_text='Reminder notes for this patient (max 500 chars)', max_length=500, null=True),
        ),
    ]
