# Generated by Django 5.2.5 on 2026-01-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0045_add_patient_status_and_sticky_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='device_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='drink',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='family_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='pharmacy_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='primary_care_physician',
            field=models.CharField(blank=True, help_text='Primary Care Physician name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='primary_care_physician_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='primary_care_physician_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='smoke',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
