# Generated by Django 5.2.5 on 2026-01-09 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0046_interest_device_serial_number_interest_drink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(help_text='Name of the patient', max_length=255)),
                ('document', models.FileField(help_text='Uploaded lab document', upload_to='lab_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='interest',
            name='medical_summary_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_summaries/'),
        ),
    ]
