# Generated by Django 5.2.5 on 2026-01-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0048_labcategory_labtest_labresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
