# Generated by Django 5.2.5 on 2026-02-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_users', '0049_add_cloudinary_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether the patient is archived from the main list'),
        ),
    ]
